env: 
  global:
    - SWIFT_BRANCH=swift-5.0.1-release
    - SWIFT_VERSION=swift-5.0.1-RELEASE
      
matrix:
  include:
    - os: linux
      dist: bionic
      service: docker
      sudo: required
      env: DOCKER_IMAGE=swift:5.0.1 SWIFT_SNAPSHOT=5.0.1
    - os: osx
      osx_image: xcode10.2
      sudo: required
      script:
        - swift build
        - swift test

notifications:
  email:
    on_success: never
    on_failure: change

after_success:
  - bash <(curl -s https://codecov.io/bash)