os:
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode10
script:
  - swift build
  - swift test
notifications:
  email:
    on_success: never
    on_failure: change
after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN